import type { Command } from 'commander';
import fs from 'fs';
import path from 'path';
import { getProjectManager } from '../lib/project.js';
import { ReviewIndexManager, getSRManager } from '../lib/spaced-repetition.js';
import type { Flashcard, FlashcardDeck, ReviewableItem } from '../types/index.js';
import { createInlineItem, createReferenceItem } from '../types/index.js';

/**
 * 复习内容添加命令
 * 支持引用式复习：只存储文档路径，复习时由 LLM 动态读取
 */
export function registerFlashcardCommand(program: Command): void {
  const flashcard = program.command('flashcard').description('闪卡管理');

  // ============ 传统闪卡命令（保留兼容） ============

  // 创建闪卡
  flashcard
    .command('create')
    .description('创建闪卡（传统方式，存储内容）')
    .requiredOption('-p, --project <name>', '项目名称')
    .requiredOption('-f, --front <text>', '正面（问题）')
    .requiredOption('-b, --back <text>', '反面（答案）')
    .option('-t, --tags <tags>', '标签（逗号分隔）')
    .option('--from <content-id>', '来源内容 ID')
    .action((options: {
      project: string;
      front: string;
      back: string;
      tags?: string;
      from?: string;
    }, cmd) => {
      const globalOptions = cmd.optsWithGlobals() as { json?: boolean };

      try {
        const manager = getProjectManager();
        const project = manager.getProject(options.project);
        if (!project) {
          throw new Error(`项目 "${options.project}" 不存在`);
        }

        const cardId = `fc-${Date.now()}`;
        const card: Flashcard = {
          id: cardId,
          front: options.front,
          back: options.back,
          tags: options.tags ? options.tags.split(',').map((t) => t.trim()) : [],
          source: {
            generatedFrom: options.from ?? 'manual',
            generatedAt: new Date().toISOString(),
            autoGenerated: false,
          },
          createdAt: new Date().toISOString(),
        };

        // 保存到卡组
        const deckPath = path.join(project.path, 'flashcards', 'deck.json');
        let deck: FlashcardDeck = { projectId: project.name, cards: [] };

        if (fs.existsSync(deckPath)) {
          try {
            deck = JSON.parse(fs.readFileSync(deckPath, 'utf-8'));
          } catch {}
        }

        deck.cards.push(card);

        const deckDir = path.dirname(deckPath);
        if (!fs.existsSync(deckDir)) {
          fs.mkdirSync(deckDir, { recursive: true });
        }
        fs.writeFileSync(deckPath, JSON.stringify(deck, null, 2), 'utf-8');

        // 添加到复习索引（使用内联存储，直接存储闪卡内容）
        const reviewManager = new ReviewIndexManager(project.path);
        const reviewItem = createInlineItem(
          cardId,
          'flashcard',
          options.front.slice(0, 50),
          options.front,
          options.back,
          card.tags
        );
        reviewManager.addItem(reviewItem);

        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-create',
            status: 'success',
            data: { card },
            context: {
              project: project.name,
              nextActions: ['运行 "learn review" 开始复习'],
            },
          }, null, 2));
        } else {
          console.log(`✅ 闪卡创建成功`);
          console.log(`🃏 ${options.front}`);
          console.log(`   答案: ${options.back}`);
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : '创建闪卡失败';
        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-create',
            status: 'error',
            error: { code: 'FLASHCARD_ERROR', message },
          }, null, 2));
        } else {
          console.error(`❌ ${message}`);
        }
        process.exit(1);
      }
    });

  // 列出闪卡
  flashcard
    .command('list')
    .description('列出闪卡')
    .requiredOption('-p, --project <name>', '项目名称')
    .option('--due', '仅显示待复习')
    .action((options: { project: string; due?: boolean }, cmd) => {
      const globalOptions = cmd.optsWithGlobals() as { json?: boolean };

      try {
        const manager = getProjectManager();
        const project = manager.getProject(options.project);
        if (!project) {
          throw new Error(`项目 "${options.project}" 不存在`);
        }

        const deckPath = path.join(project.path, 'flashcards', 'deck.json');
        if (!fs.existsSync(deckPath)) {
          if (globalOptions.json) {
            console.log(JSON.stringify({
              version: '1.0',
              timestamp: new Date().toISOString(),
              command: 'flashcard-list',
              status: 'success',
              data: { cards: [], total: 0 },
            }, null, 2));
          } else {
            console.log('暂无闪卡');
          }
          return;
        }

        const deck: FlashcardDeck = JSON.parse(fs.readFileSync(deckPath, 'utf-8'));
        let cards = deck.cards;

        if (options.due) {
          const reviewManager = new ReviewIndexManager(project.path);
          const index = reviewManager.loadIndex();
          const srManager = getSRManager();
          const dueItems = srManager.getDueItems(index);
          const dueIds = new Set(dueItems.map((i) => i.id));
          cards = cards.filter((c) => dueIds.has(c.id));
        }

        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-list',
            status: 'success',
            data: { cards, total: cards.length },
          }, null, 2));
        } else {
          if (cards.length === 0) {
            console.log('暂无闪卡');
            return;
          }

          console.log(`🃏 闪卡列表 (${cards.length} 张)\n`);
          cards.forEach((card, i) => {
            console.log(`${i + 1}. ${card.front}`);
            console.log(`   答案: ${card.back}`);
            if (card.tags.length > 0) {
              console.log(`   标签: ${card.tags.join(', ')}`);
            }
            console.log('');
          });
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : '获取闪卡失败';
        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-list',
            status: 'error',
            error: { code: 'FLASHCARD_ERROR', message },
          }, null, 2));
        } else {
          console.error(`❌ ${message}`);
        }
        process.exit(1);
      }
    });

  // ============ 新增：引用式复习命令 ============

  // 添加笔记到复习计划
  flashcard
    .command('add-note')
    .description('添加笔记到复习计划（引用式，复习时 LLM 动态读取）')
    .requiredOption('-p, --project <name>', '项目名称')
    .requiredOption('-f, --file <path>', '笔记文件路径')
    .option('-s, --section <id>', '章节锚点')
    .option('-t, --title <title>', '标题')
    .option('--tags <tags>', '标签（逗号分隔）')
    .action((options: {
      project: string;
      file: string;
      section?: string;
      title?: string;
      tags?: string;
    }, cmd) => {
      const globalOptions = cmd.optsWithGlobals() as { json?: boolean };

      try {
        const manager = getProjectManager();
        const project = manager.getProject(options.project);
        if (!project) {
          throw new Error(`项目 "${options.project}" 不存在`);
        }

        // 验证文件存在
        const notePath = path.join(project.path, options.file);
        if (!fs.existsSync(notePath)) {
          throw new Error(`笔记不存在: ${options.file}`);
        }

        // 提取摘要（前 100 字符）
        const content = fs.readFileSync(notePath, 'utf-8');
        const excerpt = content.slice(0, 100).replace(/\n/g, ' ');

        // 确定标题
        const title = options.title || path.basename(options.file, '.md');

        // 创建引用式复习项
        const itemId = `note-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
        const reviewItem = createReferenceItem(
          itemId,
          'note',
          title,
          options.file,
          {
            sectionId: options.section,
            excerpt,
          },
          options.tags ? options.tags.split(',').map((t) => t.trim()) : []
        );

        // 保存到索引
        const reviewManager = new ReviewIndexManager(project.path);
        reviewManager.addItem(reviewItem);

        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-add-note',
            status: 'success',
            data: {
              id: reviewItem.id,
              type: 'note',
              title: reviewItem.title,
              reference: reviewItem.reference,
            },
            context: {
              project: project.name,
              nextActions: ['运行 "learn review" 开始复习'],
            },
          }, null, 2));
        } else {
          console.log(`✅ 笔记已添加到复习计划`);
          console.log(`📝 ${title}`);
          console.log(`📁 文件: ${options.file}`);
          console.log(`   复习时将自动读取笔记内容`);
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : '添加笔记失败';
        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-add-note',
            status: 'error',
            error: { code: 'FLASHCARD_ERROR', message },
          }, null, 2));
        } else {
          console.error(`❌ ${message}`);
        }
        process.exit(1);
      }
    });

  // 添加知识点到复习计划
  flashcard
    .command('add-knowledge')
    .description('添加知识点到复习计划（引用式）')
    .requiredOption('-p, --project <name>', '项目名称')
    .requiredOption('-f, --file <path>', '笔记文件路径')
    .requiredOption('-t, --title <title>', '知识点标题')
    .option('--start <line>', '起始行号', parseInt)
    .option('--end <line>', '结束行号', parseInt)
    .option('--tags <tags>', '标签（逗号分隔）')
    .action((options: {
      project: string;
      file: string;
      title: string;
      start?: number;
      end?: number;
      tags?: string;
    }, cmd) => {
      const globalOptions = cmd.optsWithGlobals() as { json?: boolean };

      try {
        const manager = getProjectManager();
        const project = manager.getProject(options.project);
        if (!project) {
          throw new Error(`项目 "${options.project}" 不存在`);
        }

        const notePath = path.join(project.path, options.file);
        if (!fs.existsSync(notePath)) {
          throw new Error(`笔记不存在: ${options.file}`);
        }

        // 提取指定行范围的内容作为摘要
        let excerpt = '';
        if (options.start !== undefined) {
          const lines = fs.readFileSync(notePath, 'utf-8').split('\n');
          const end = options.end || Math.min(options.start + 10, lines.length);
          excerpt = lines.slice(options.start - 1, end).join('\n').slice(0, 200);
        }

        const itemId = `kp-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
        const reviewItem = createReferenceItem(
          itemId,
          'knowledge-point',
          options.title,
          options.file,
          {
            lineStart: options.start,
            lineEnd: options.end,
            excerpt: excerpt || undefined,
          },
          options.tags ? options.tags.split(',').map((t) => t.trim()) : []
        );

        const reviewManager = new ReviewIndexManager(project.path);
        reviewManager.addItem(reviewItem);

        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-add-knowledge',
            status: 'success',
            data: {
              id: reviewItem.id,
              type: 'knowledge-point',
              title: reviewItem.title,
              reference: reviewItem.reference,
            },
            context: {
              project: project.name,
              nextActions: ['运行 "learn review" 开始复习'],
            },
          }, null, 2));
        } else {
          console.log(`✅ 知识点已添加到复习计划`);
          console.log(`💡 ${options.title}`);
          console.log(`📁 文件: ${options.file}`);
          if (options.start) {
            console.log(`   行范围: ${options.start}${options.end ? `-${options.end}` : ''}`);
          }
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : '添加知识点失败';
        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-add-knowledge',
            status: 'error',
            error: { code: 'FLASHCARD_ERROR', message },
          }, null, 2));
        } else {
          console.error(`❌ ${message}`);
        }
        process.exit(1);
      }
    });

  // 添加项目实践到复习计划
  flashcard
    .command('add-project')
    .description('添加实践项目到复习计划')
    .requiredOption('-p, --project <name>', '学习项目名称')
    .requiredOption('-d, --dir <path>', '实践项目目录')
    .requiredOption('-t, --title <title>', '项目标题')
    .option('--tags <tags>', '标签（逗号分隔）')
    .action((options: {
      project: string;
      dir: string;
      title: string;
      tags?: string;
    }, cmd) => {
      const globalOptions = cmd.optsWithGlobals() as { json?: boolean };

      try {
        const manager = getProjectManager();
        const learningProject = manager.getProject(options.project);
        if (!learningProject) {
          throw new Error(`项目 "${options.project}" 不存在`);
        }

        const projectDir = path.join(learningProject.path, options.dir);
        if (!fs.existsSync(projectDir)) {
          throw new Error(`实践项目目录不存在: ${options.dir}`);
        }

        const itemId = `proj-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
        const reviewItem = createReferenceItem(
          itemId,
          'project',
          options.title,
          options.dir,
          undefined,
          options.tags ? options.tags.split(',').map((t) => t.trim()) : []
        );

        const reviewManager = new ReviewIndexManager(learningProject.path);
        reviewManager.addItem(reviewItem);

        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-add-project',
            status: 'success',
            data: {
              id: reviewItem.id,
              type: 'project',
              title: reviewItem.title,
              reference: reviewItem.reference,
            },
          }, null, 2));
        } else {
          console.log(`✅ 实践项目已添加到复习计划`);
          console.log(`🎯 ${options.title}`);
          console.log(`📁 目录: ${options.dir}`);
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : '添加实践项目失败';
        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-add-project',
            status: 'error',
            error: { code: 'FLASHCARD_ERROR', message },
          }, null, 2));
        } else {
          console.error(`❌ ${message}`);
        }
        process.exit(1);
      }
    });

  // 列出所有复习项（包括引用式）
  flashcard
    .command('list-all')
    .description('列出所有复习项（包括笔记、知识点、项目）')
    .requiredOption('-p, --project <name>', '项目名称')
    .option('--type <type>', '类型筛选 (note/knowledge-point/project/flashcard)')
    .action((options: { project: string; type?: string }, cmd) => {
      const globalOptions = cmd.optsWithGlobals() as { json?: boolean };

      try {
        const manager = getProjectManager();
        const project = manager.getProject(options.project);
        if (!project) {
          throw new Error(`项目 "${options.project}" 不存在`);
        }

        const reviewManager = new ReviewIndexManager(project.path);
        const index = reviewManager.loadIndex();

        let items = index.items;
        if (options.type) {
          items = items.filter((i) => i.type === options.type);
        }

        const typeEmoji: Record<string, string> = {
          note: '📝',
          'knowledge-point': '💡',
          project: '🎯',
          flashcard: '🃏',
        };

        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-list-all',
            status: 'success',
            data: { items, total: items.length },
          }, null, 2));
        } else {
          if (items.length === 0) {
            console.log('暂无复习项');
            return;
          }

          console.log(`📚 复习项列表 (${items.length} 项)\n`);

          // 按类型分组
          const grouped = items.reduce((acc, item) => {
            if (!acc[item.type]) acc[item.type] = [];
            acc[item.type].push(item);
            return acc;
          }, {} as Record<string, typeof items>);

          for (const [type, typeItems] of Object.entries(grouped)) {
            console.log(`${typeEmoji[type] || '📄'} ${type} (${typeItems.length} 项)`);
            typeItems.forEach((item, i) => {
              console.log(`   ${i + 1}. ${item.title}`);
              const location = item.storageType === 'inline'
                ? '内联内容'
                : item.reference?.documentPath || '未知';
              console.log(`      来源: ${location}`);
            });
            console.log('');
          }
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : '获取复习项失败';
        if (globalOptions.json) {
          console.log(JSON.stringify({
            version: '1.0',
            timestamp: new Date().toISOString(),
            command: 'flashcard-list-all',
            status: 'error',
            error: { code: 'FLASHCARD_ERROR', message },
          }, null, 2));
        } else {
          console.error(`❌ ${message}`);
        }
        process.exit(1);
      }
    });
}
