/**
 * Flashcard 数据结构
 */
export interface Flashcard {
  /** 卡片 ID */
  id: string;
  /** 正面（问题） */
  front: string;
  /** 反面（答案） */
  back: string;
  /** 标签 */
  tags: string[];
  /** 来源信息 */
  source: {
    /** 来源内容 ID */
    generatedFrom: string;
    /** 生成时间 */
    generatedAt: string;
    /** 是否自动生成 */
    autoGenerated: boolean;
  };
  /** 创建时间 */
  createdAt: string;
}

/**
 * 闪卡卡组
 */
export interface FlashcardDeck {
  /** 项目 ID */
  projectId: string;
  /** 卡片列表 */
  cards: Flashcard[];
}

/**
 * 学习会话
 */
export interface StudySession {
  /** 会话 ID */
  id: string;
  /** 项目名称 */
  projectName: string;
  /** 开始时间 */
  startedAt: string;
  /** 结束时间 */
  endedAt?: string;
  /** 学习时长（分钟） */
  duration?: number;
  /** 学习笔记 */
  note?: string;
  /** 学习摘要 */
  summary?: string;
  /** 绑定的学习单元 */
  unitId?: string;
  /** 会话产生的证据 ID */
  evidenceIds?: string[];
}

/**
 * 学习统计
 */
export interface LearningStats {
  /** 总学习时长（小时） */
  totalHours: number;
  /** 总会话数 */
  totalSessions: number;
  /** 总笔记数 */
  totalNotes: number;
  /** 总闪卡数 */
  totalFlashcards: number;
  /** 已掌握闪卡数 */
  masteredFlashcards: number;
  /** 连续学习天数 */
  streakDays: number;
  /** 项目数 */
  projectCount: number;
  /** 本周学习时长 */
  weeklyHours: number;
  /** 本月学习时长 */
  monthlyHours: number;
}

/**
 * Agent 输出格式
 */
export interface AgentOutput<T> {
  /** 版本号 */
  version: '1.0';
  /** 时间戳 */
  timestamp: string;
  /** 执行的命令 */
  command: string;
  /** 状态 */
  status: 'success' | 'error' | 'pending';
  /** 数据 */
  data: T;
  /** 上下文信息 */
  context?: {
    project?: string;
    stage?: string;
    nextActions?: string[];
  };
  /** 错误信息 */
  error?: {
    code: string;
    message: string;
  };
}

/**
 * 创建 Agent 输出
 */
export function createAgentOutput<T>(
  command: string,
  data: T,
  options?: {
    status?: 'success' | 'error' | 'pending';
    context?: AgentOutput<T>['context'];
    error?: AgentOutput<T>['error'];
  }
): AgentOutput<T> {
  return {
    version: '1.0',
    timestamp: new Date().toISOString(),
    command,
    status: options?.status ?? 'success',
    data,
    context: options?.context,
    error: options?.error,
  };
}

/**
 * 创建错误输出
 */
export function createErrorOutput(
  command: string,
  code: string,
  message: string
): AgentOutput<null> {
  return createAgentOutput(command, null, {
    status: 'error',
    error: { code, message },
  });
}
